---
title: "Untitled"
output: html_document
---

```{r}
load(paste0(getwd(), "/data/reference/reference_data.rdata"))
```

```{r empty risk plot}
combs %>%
  filter(log.comb.or <= quantiles[1] | log.comb.or >= quantiles[2]) %>% 
  ggplot() +
  aes(x = log.comb.or, y = index) +
  geom_line(aes(color = log.comb.or,
                size = risk_plot_geom_line_size)) +
  scale_colour_gradient2(low = colorpalette[1],
                         mid = colorpalette[2],
                         high = colorpalette[3]) +
  theme_minimal() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.ticks.y=element_blank(),
        axis.text.y = element_blank(),
        axis.title.y=element_blank(),
        legend.position = "none",
        plot.background = element_rect(fill = "white"),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())
```

```{r RISK PLOT}
calculated_risk = 1
#log(100)

temp = combs %>% 
  filter(!log.comb.or <= quantiles[1] & !log.comb.or >= quantiles[2])
  
temp %>% 
  ggplot() +
  aes(x = log.comb.or, y = index) +
  geom_line(aes(color = log.comb.or,
                size = risk_plot_geom_line_size)) +
  scale_colour_gradient2(low = "green",
                         mid = "yellow",
                         high = "red",
                         midpoint = (range(temp$log.comb.or)[1] + range(temp$log.comb.or)[2]) / 2) +
  geom_point(aes(x = log(calculated_risk), y = 1), 
             color = "black",
             shape = risk_plot_geom_point_shape,
             size = risk_plot_geom_point_size) +
  theme_minimal() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.ticks.y=element_blank(),
        axis.text.y = element_blank(),
        axis.title.y=element_blank(),
        legend.position = "none",
        plot.background = element_rect(fill = "white"),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())
```


```{r risk plot}
calculated_risk = 1

combs %>% 
  
  ggplot() +
  aes(x = log.comb.or, y = index) +
  geom_line(aes(color = log.comb.or,
                size = risk_plot_geom_line_size)) +
  scale_colour_gradient2(low = colorpalette[1],
                         mid = colorpalette[2],
                         high = colorpalette[3])+
  geom_point(aes(x = log(calculated_risk), y = 1), 
             color = "black",
             shape = risk_plot_geom_point_shape,
             size = risk_plot_geom_point_size) +
  theme_minimal() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.ticks.y=element_blank(),
        axis.text.y = element_blank(),
        axis.title.y=element_blank(),
        legend.position = "none",
        plot.background = element_rect(fill = "white"),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())
```

```{r}
if (log(calculated_risk) > 7) {
  calculated_risk = exp(7)
}

x <- df_ctrl$log.comb.or
y <- density(x, n = 2^12,
             adjust = 0.9)

ggplot(data.frame(x = y$x, y = y$y), aes(x, y)) +
  geom_line(colour = "grey25",
            size = 1.2) + 
  geom_segment(aes(xend = x, yend = 0, colour = x)) + 
  scale_color_gradient2(low = colorpalette[1],
                        mid = colorpalette[2],
                        high = colorpalette[3]) +
  geom_vline(xintercept = log(calculated_risk),
             size = 1.25,
             color = "red") +
  geom_vline(xintercept = quantiles[1], linetype = 5) +
  geom_vline(xintercept = quantiles[2], linetype = 5) +
  annotate(geom = "text",
           x = quantiles[1] - 1,
           y = 0.09,
           label = "Low risk\nzone") +
  annotate(geom = "text",
           x = quantiles[2] + 1,
           y = 0.09,
           label = "High risk\nzone") +
  annotate(geom = "text",
           x = log(calculated_risk) - 1,
           y = 0.15,
           label = "Subject →") +
  theme_classic() +
  theme(text = element_text(size = density_text_size),
        legend.position = "none",
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank()) +
  scale_x_continuous(breaks = NULL,
                     limits = lims) +
  scale_y_continuous(breaks = NULL) +
  labs(y = "Frequency",
       x = "Risk",
       title = "Risk distribution in general population")




```

```{r}
quantiles = quantile(df_ctrl$log.comb.or, probs = c(0.1, 0.9))

df_ctrl = df_ctrl %>% 
  mutate(ext = case_when(log.comb.or <= quantile(df_ctrl$log.comb.or, probs = 0.1) ~ "low",
                         log.comb.or >= quantile(df_ctrl$log.comb.or, probs = 0.9) ~ "high",
                         TRUE ~ "normal"))

df_ctrl %>% 
  ggplot() +
  aes(x = log.comb.or) +
  geom_density() +
  geom_vline(xintercept = quantiles[1]) +
  geom_vline(xintercept = quantiles[2])
```

```{r}
quantiles
df_casi
df_casi %>% 
  mutate(ext = case_when(log.comb.or <= quantiles[1] ~ "low",
                         log.comb.or >= quantiles[2] ~ "high",
                         TRUE ~ "normal")) %>% 
  count(ext)


df_casi %>%
  ggplot() +
  aes(x = log.comb.or) +
  geom_density() +
  geom_vline(xintercept = quantiles[1]) +
  geom_vline(xintercept = quantiles[2]) +
  annotate(geom = "text",
           x = 0,
           y = 0.1,
           label = "ciao")
```

```{r}
quantiles = quantile(df_ctrl$log.comb.or, probs = c(0.1, 0.9))

exp(quantiles)

cat("low=",round(sum(df_casi$log.comb.or <= quantiles[1])/nrow(df_casi) * 100, 2),"%\n")
cat("high=",round(sum(df_casi$log.comb.or >= quantiles[2])/nrow(df_casi) * 100, 2),"%")
```

# quante volte il rischio del soggetto è superiore a quello della pop gen?

```{r}
calculated_risk = 10

calculated_risk / mean(df_ctrl$comb.or)

# MAH
```

